import './globals.css'
import { Inter } from 'next/font/google'
import { Nav } from '@/components'

const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Daily Health Tracker',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} text-neutral-700 dark:text-neutral-200 bg-neutral-200 dark:bg-neutral-900`}>
        <Nav />
        {children}
      </body>
    </html>
  )
}
